# The basics
- Resource from: NumPy.org

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

For example, the array for the coordinates of a point in 3D space, [1, 2, 1], has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

In [ ]:
[[1., 0., 0.],
 [0., 1., 2.]]

NumPy’s array class is called *ndarray*. It is also known by the alias *array*. Note that *numpy.array* is not the same as the Standard Python Library class *array.array*, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

**ndarray.ndim**
- the number of axes (dimensions) of the array.

**ndarray.shape**
- the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, **shape** will be **(n,m)**. The length of the **shape** tuple is therefore the number of axes, **ndim**.

**ndarray.size**
- the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**
- an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**
- the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [1]:
import numpy as np

In [14]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [9]:
# Get Shape
b.shape

(2, 3)

In [12]:
#Get Type
a.dtype

dtype('int16')

In [15]:
# Get Size
a.itemsize

4

In [18]:
# Get total size
# a.size * a.itemsize
a.nbytes

12

# Accessing/Changing specific elements, row, columns, ect

In [21]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# Get a specifc element [r, c]
a[1, 5]

13

In [25]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [27]:
# Gettng a little more fancy [startiindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [32]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
# 3D Example
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Get specific element (work outside in)
b[0, 1, :]

array([3, 4])

In [37]:
# replace
b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [48]:
# All 0s matrix
np.zeros((5, 2,3,))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [54]:
# any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [56]:
# Any other number (full_like)
np.full_like(a, 4)
# or np.like(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [59]:
# Random decimal number
np.random.rand(4,2,3)

array([[[0.30735055, 0.46629695, 0.69740648],
        [0.27691196, 0.43198414, 0.03816841]],

       [[0.79954496, 0.04168042, 0.55883159],
        [0.16459549, 0.82245849, 0.5371141 ]],

       [[0.03046472, 0.46390354, 0.98322256],
        [0.65741421, 0.46925327, 0.79623683]],

       [[0.51947176, 0.29667353, 0.90278404],
        [0.66503041, 0.54707086, 0.88255804]]])

In [60]:
# Random decimal number (sample)
np.random.random_sample(a.shape)

array([[0.25926514, 0.65770838, 0.25913817, 0.32237612, 0.16454808,
        0.50697994, 0.70043242],
       [0.98320069, 0.86262721, 0.06464066, 0.21856665, 0.14658529,
        0.52788822, 0.0606115 ]])

In [70]:
# Random Interger values
np.random.randint(-4,7, size=(3,2))

array([[-3,  1],
       [-1, -3],
       [-2,  0]])

In [72]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [77]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [83]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [89]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [91]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [100]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [95]:
a + 2

array([3, 4, 5, 6])

In [96]:
a - 2

array([-1,  0,  1,  2])

In [97]:
a * 2

array([2, 4, 6, 8])

In [98]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [101]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [102]:
a ** 2

array([ 1,  4,  9, 16])

In [103]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [104]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [110]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [112]:
# Fine the determinant
c = np.identity(3)
np.linalg.det(c)

1.0